-- Phase 5: prepare the migrated tables so the Python admin can write to them.
-- The initial import kept ids as plain integers; make them auto-increment
-- (continuing past the imported max) and add the dedup key the ingest relies on.

ALTER TABLE destinations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('destinations', 'id'),
              GREATEST((SELECT max(id) FROM destinations), 1));

ALTER TABLE attractions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('attractions', 'id'),
              GREATEST((SELECT max(id) FROM attractions), 1));

ALTER TABLE attractions ADD CONSTRAINT attractions_osm_key UNIQUE (osm_type, osm_id);
