-- NanaBanana — Postgres schema for Supabase.
-- Two groups:
--   1) public read-only data (destinations, attractions, settings, tickets) —
--      migrated once from the SQLite DB; read by the consumer app, written by
--      the admin (service role).
--   2) per-user data (profiles, trips, hotels) — protected by Row Level
--      Security so a user can only ever touch their own rows.
--
-- Apply in the Supabase SQL editor (or via the migration script).

-- ---------- public reference data ----------

create table if not exists destinations (
  id                        integer primary key,   -- preserved from SQLite
  country                   text,
  region                    text,
  city                      text,
  city_he                   text,
  country_he                text,
  name_he                   text,
  name_en                   text,
  lat                       double precision,
  lng                       double precision,
  description_he            text,
  best_months               jsonb,
  israeli_popularity_score  integer,
  timezone                  text,
  currency                  text,
  language                  text,
  created_at                timestamptz default now()
);

create table if not exists attractions (
  id                 integer primary key,           -- preserved from SQLite
  destination_id     integer references destinations(id),
  name_he            text,
  name_en            text,
  lat                double precision,
  lng                double precision,
  category           text,
  subcategory        text,
  indoor_outdoor     text,
  duration_minutes   integer,
  price_usd          double precision,
  min_age            integer,
  max_age            integer,
  family_score       integer,
  physical_intensity integer,
  opening_hours      text,
  rating_google      double precision,
  rating_count       integer,
  description_he     text,
  tips_he            text,
  website            text,
  video_links        jsonb,
  info_sources       jsonb,
  osm_id             text,
  osm_type           text,
  google_place_id    text,
  quality_keep       integer,
  enriched_at        timestamptz,
  image_url          text,
  image_checked_at   timestamptz,
  tagline_he         text,
  best_season        text,
  best_time_he       text,
  dress_he           text,
  cost_level         integer,
  must_see           integer,
  is_duplicate       integer,
  created_at         timestamptz default now()
);
create index if not exists idx_attr_dest on attractions(destination_id);
create index if not exists idx_attr_cat  on attractions(category);
create index if not exists idx_attr_keep on attractions(quality_keep);

create table if not exists settings (
  key   text primary key,
  value text
);

create table if not exists tickets (
  id         integer generated by default as identity primary key,
  type       text,
  title      text,
  body       text,
  images     jsonb,
  status     text default 'open',   -- open | done (pending approval) | approved
  notes      text,                  -- team verification / rejection notes
  parent_id  integer,               -- links a follow-up to its original ticket
  created_at timestamptz default now()
);

-- ---------- per-user data (RLS) ----------

create table if not exists profiles (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  data       jsonb not null default '{}'::jsonb,   -- FamilyProfile shape
  updated_at timestamptz default now()
);

create table if not exists trips (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users(id) on delete cascade,
  title          text,
  mode           text,                              -- preferences | hotels
  city           text,
  city_he        text,
  country        text,
  destination_id integer,
  days           integer,
  month          integer,
  segments       jsonb,                             -- Segment[] (multi-city)
  itinerary      jsonb,                             -- full Itinerary
  created_at     timestamptz default now(),
  updated_at     timestamptz default now()
);
create index if not exists idx_trips_user on trips(user_id);

create table if not exists hotels (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users(id) on delete cascade,
  trip_id    uuid references trips(id) on delete cascade,
  segment_id text,                                  -- which leg (client segment id)
  name       text,
  label      text,
  city       text,
  country    text,
  lat        double precision,
  lng        double precision,
  check_in   date,
  check_out  date,
  created_at timestamptz default now()
);
create index if not exists idx_hotels_user on hotels(user_id);
create index if not exists idx_hotels_trip on hotels(trip_id);

-- ---------- Row Level Security ----------
-- Public data: readable by anyone (anon), writable only by the service role
-- (the admin/pipeline). No anon write policies => anon cannot write.
alter table destinations enable row level security;
alter table attractions  enable row level security;
alter table settings      enable row level security;

drop policy if exists destinations_read on destinations;
drop policy if exists attractions_read  on attractions;
drop policy if exists settings_read     on settings;
create policy destinations_read on destinations for select using (true);
create policy attractions_read  on attractions  for select using (true);
create policy settings_read     on settings     for select using (true);

-- User data: each user sees and edits only their own rows.
alter table profiles enable row level security;
alter table trips    enable row level security;
alter table hotels   enable row level security;

drop policy if exists profiles_owner on profiles;
create policy profiles_owner on profiles
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists trips_owner on trips;
create policy trips_owner on trips
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists hotels_owner on hotels;
create policy hotels_owner on hotels
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- tickets: internal admin data — no anon access; reached only via service role.
alter table tickets enable row level security;
